/**
 * Small, vendor-specific Claude surface generated by `ax init`.
 *
 * This is intentionally a foundation, not a copy of one team's private
 * workflow. It gives a new repository the same kinds of entrypoints as a
 * mature workspace while keeping project facts in `.ax/context` and leaving
 * existing files untouched.
 */

export interface ClaudePackFile {
  path: string;
  contents: string;
  note: string;
}

const claude = (name: string, profile: string) => `# ${name} — Claude Code workspace

Read the repository root [AGENTS.md](../AGENTS.md) first. It is the vendor-neutral
contract for this project. Then load only the task-relevant context from
\`.ax/context/\` and inspect the source before editing.

Profile: \`${profile}\` (Experimental)

## Session flow

1. Locate the requested feature and read its direct dependencies.
2. State a small plan when more than one file is involved.
3. Make the smallest compatible change.
4. Run the narrowest useful checks, then broader checks when justified.
5. Report changed files, actual commands and results, failures, and unrun checks.

Do not claim that an unrun check passed. Do not start unrelated agents, tools,
migrations, deployments, or database work merely because they are described here.

## Useful surfaces

- Rules: [base](rules/base-rule.md), [security](rules/security.md), and [verification](rules/verification.md).
- Rules: [base](rules/base-rule.md), [security](rules/security.md), [verification](rules/verification.md), and [UI](rules/ui.md).
- Procedures: [develop](skills/develop/SKILL.md), [plan](skills/dev-plan/SKILL.md), [review](skills/code-review/SKILL.md), and [UI review](skills/ui-review/SKILL.md).
- Roles: [planner](agents/planner.md), [developer](agents/developer.md), [frontend](agents/frontend.md), [reviewer](agents/reviewer.md), and [qa](agents/qa.md).
- Project metadata: [config/project.yaml](config/project.yaml).

These files are instructions for a human or an assistant. They do not grant
permissions by themselves; the Harness declaration and explicit user direction
remain authoritative.
`;

const settings = `{
  "$schema": "https://json.schemastore.org/claude-code-settings.json",
  "permissions": {
    "allow": [
      "Bash(git status:*)",
      "Bash(git diff:*)",
      "Bash(git log:*)"
    ],
    "deny": [
      "Bash(git push --force*)",
      "Bash(git reset --hard*)",
      "Bash(git checkout -- *)",
      "Read(**/.env)",
      "Read(**/.env.*)",
      "Read(**/*.pem)",
      "Read(**/*.key)",
      "Read(**/*.jks)",
      "Read(**/.ssh/**)",
      "Read(**/secrets/**)"
    ]
  }
}
`;

const projectConfig = (name: string, profile: string) => `# Generated by ax init. Keep project facts here; keep secrets out.
workspaceName: ${name}
profile: ${profile}
outputDir: .ax/work

# Add a short description and the conventions an assistant must know.
role: "Describe this repository and the people it serves."

# These are reminders for the Claude surface, not permission grants.
workflow:
  planBeforeEdit: true
  verifyAfterEdit: true
  reportUnrunChecks: true

# Add project-specific guides under .claude/docs/ and list them here.
guides: []
`;

const baseRule = `# Base rule

- Read existing instructions and the smallest relevant code surface first.
- Preserve public behavior, data contracts, authorization, and local conventions.
- Prefer a focused patch over a broad refactor.
- Reuse existing components, helpers, and types before creating new ones.
- Never expose credentials, tokens, private keys, or real environment values.
- Never commit, push, deploy, migrate, or write a database without explicit direction.
- Keep facts in project context documents instead of inventing assumptions.
`;

const securityRule = `# Security rule

- Treat request input, file paths, database identifiers, and external responses as untrusted.
- Use the project's existing authentication and authorization boundaries.
- Do not read secret files or copy secret values into logs, prompts, context, or code.
- Use parameterized database access and preserve ownership predicates.
- Flag a security concern with its file and consequence; do not silently weaken a guard.
`;

const verificationRule = `# Verification rule

- Run the smallest relevant check first, then the declared build or full suite when needed.
- A command being available is not evidence that it passed.
- Distinguish passed, failed, unavailable, and unrun checks in reports.
- For UI work, inspect loading, empty, error, keyboard, and responsive states.
- For data work, verify both successful and rejected paths without using a shared database.
`;

const uiRule = `# UI rule

- Preserve the existing product language, visual system, and interaction patterns.
- Inspect the target page and its direct components before changing shared UI.
- Reuse existing components, tokens, icons, typography, and loading/error states.
- Design mobile-first and check at approximately 375px, 768px, 1024px, and 1440px.
- Keep keyboard navigation, visible focus, semantic labels, accessible names, and readable contrast.
- Keep touch targets usable and prevent accidental horizontal overflow.
- Treat loading, empty, error, unauthorized, and populated states as part of the UI.
- Keep animation subtle and useful. Do not add visual noise, broad redesigns, or dependencies for simple effects.
- Do not change API contracts, authentication, authorization, or database behavior during a UI-only task.
`;

const developSkill = `# Develop

Use this procedure for implementation work:

1. Restate the requested behavior and identify the affected boundary.
2. Read direct dependencies, existing tests, and the relevant context document.
3. Plan the smallest coherent edit.
4. Implement without changing unrelated contracts.
5. Run targeted verification and inspect the final diff.
6. Report what changed and what remains unverified.
`;

const planSkill = `# Dev plan

Produce a short plan before a multi-file change. Include the files or boundaries
to inspect, the behavior to preserve, the checks to run, and any decision that
needs human input. A plan is not permission to execute tools or migrations.
`;

const reviewSkill = `# Code review

Review the diff before suggesting cleanup. Prioritize correctness, security,
authorization, data integrity, public contracts, and missing verification. Each
finding must name a location, explain the impact, and state a concrete fix. Do
not rewrite code just to express a preference.
`;

const uiReviewSkill = `# UI review

Review a frontend change in this order:

1. Confirm the requested flow and inspect direct page/component dependencies.
2. Check hierarchy, spacing, typography, states, responsive layout, and reuse of existing primitives.
3. Check keyboard behavior, focus visibility, labels, contrast, image alternatives, and touch targets.
4. Check that client/server boundaries, API usage, auth behavior, and data ownership remain intact.
5. Report findings with a file location, user impact, and a concrete recommendation.

Do not redesign unrelated screens or treat a successful build as proof of visual correctness.
`;

const role = (title: string, focus: string) => `# ${title}

Role: ${focus}

Read-only by default. Follow the root instructions and relevant skill. Return
evidence with file locations and distinguish observed facts from assumptions.
`;

export function claudePack(name: string, profile: string): ClaudePackFile[] {
  return [
    { path: '.claude/CLAUDE.md', contents: claude(name, profile), note: 'Claude entrypoint' },
    { path: '.claude/settings.json', contents: settings, note: 'conservative Claude permissions' },
    { path: '.claude/config/project.yaml', contents: projectConfig(name, profile), note: 'workspace metadata' },
    { path: '.claude/rules/base-rule.md', contents: baseRule, note: 'shared engineering rules' },
    { path: '.claude/rules/security.md', contents: securityRule, note: 'security rules' },
    { path: '.claude/rules/verification.md', contents: verificationRule, note: 'verification rules' },
    { path: '.claude/rules/ui.md', contents: uiRule, note: 'UI and accessibility rules' },
    { path: '.claude/skills/develop/SKILL.md', contents: developSkill, note: 'implementation procedure' },
    { path: '.claude/skills/dev-plan/SKILL.md', contents: planSkill, note: 'planning procedure' },
    { path: '.claude/skills/code-review/SKILL.md', contents: reviewSkill, note: 'review procedure' },
    { path: '.claude/skills/ui-review/SKILL.md', contents: uiReviewSkill, note: 'frontend review procedure' },
    { path: '.claude/agents/planner.md', contents: role('Planner', 'turn a request into a bounded, reviewable plan'), note: 'planning role' },
    { path: '.claude/agents/developer.md', contents: role('Developer', 'implement a requested change within the declared architecture'), note: 'implementation role' },
    { path: '.claude/agents/frontend.md', contents: role('Frontend developer', 'implement focused, responsive, accessible interface changes using existing patterns'), note: 'frontend role' },
    { path: '.claude/agents/reviewer.md', contents: role('Reviewer', 'find correctness, security, contract, and verification risks in a diff'), note: 'review role' },
    { path: '.claude/agents/qa.md', contents: role('QA reviewer', 'design targeted checks and report evidence without inventing results'), note: 'quality role' },
    { path: '.claude/docs/README.md', contents: '# Project documentation\n\nPut stable, project-specific guides here. Link them from `.claude/config/project.yaml` and the relevant context file. Do not copy secrets or generated run output.\n', note: 'documentation index' },
    { path: '.claude/.gitignore', contents: 'work/\n\n', note: 'local Claude work output' },
  ];
}
