/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Identifier = string;
export type Line = string;
/**
 * Relative Markdown path using forward slashes. Absolute paths and parent traversal are forbidden.
 */
export type RepoPath = string;
/**
 * @minItems 1
 * @maxItems 32
 */
export type Notes = [Note, ...Note[]];
export type Note = string;

/**
 * AX Harness v1 vendor adapter. An adapter describes where a vendor tool reads its instructions and which shared documents that entrypoint defers to. An adapter is a surface, never a competing architecture, and holds no capabilities of its own.
 */
export interface AdapterDefinition {
  schemaVersion: 1;
  id: Identifier;
  vendor: Line;
  status: "implemented" | "experimental" | "planned";
  /**
   * Repository-relative file the vendor tool loads first.
   */
  entrypoint: string;
  /**
   * Vendor-neutral documents this adapter surfaces to its tool. All must exist in the repository.
   *
   * @minItems 1
   * @maxItems 16
   */
  sharedInstructions:
    | [RepoPath]
    | [RepoPath, RepoPath]
    | [RepoPath, RepoPath, RepoPath]
    | [RepoPath, RepoPath, RepoPath, RepoPath]
    | [RepoPath, RepoPath, RepoPath, RepoPath, RepoPath]
    | [RepoPath, RepoPath, RepoPath, RepoPath, RepoPath, RepoPath]
    | [RepoPath, RepoPath, RepoPath, RepoPath, RepoPath, RepoPath, RepoPath]
    | [RepoPath, RepoPath, RepoPath, RepoPath, RepoPath, RepoPath, RepoPath, RepoPath]
    | [RepoPath, RepoPath, RepoPath, RepoPath, RepoPath, RepoPath, RepoPath, RepoPath, RepoPath]
    | [RepoPath, RepoPath, RepoPath, RepoPath, RepoPath, RepoPath, RepoPath, RepoPath, RepoPath, RepoPath]
    | [RepoPath, RepoPath, RepoPath, RepoPath, RepoPath, RepoPath, RepoPath, RepoPath, RepoPath, RepoPath, RepoPath]
    | [
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath
      ]
    | [
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath
      ]
    | [
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath
      ]
    | [
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath
      ]
    | [
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath,
        RepoPath
      ];
  notes: Notes;
}
