/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Identifier = string;
export type Line = string;
export type Text = string;
/**
 * What this role owns. Roles must not overlap in ownership.
 *
 * @minItems 1
 * @maxItems 32
 */
export type Notes = [Note, ...Note[]];
export type Note = string;
/**
 * What must be loaded before this role can work usefully.
 *
 * @minItems 1
 * @maxItems 32
 */
export type Notes1 = [Note, ...Note[]];
/**
 * Actions this role must never take, stated for readers as well as tools.
 *
 * @minItems 1
 * @maxItems 32
 */
export type Notes2 = [Note, ...Note[]];
/**
 * @minItems 1
 * @maxItems 32
 */
export type Notes3 = [Note, ...Note[]];
/**
 * Conditions that require stopping and returning to a human.
 *
 * @minItems 1
 * @maxItems 32
 */
export type Notes4 = [Note, ...Note[]];

/**
 * AX Harness v1 agent. An agent is an engineering role with bounded responsibilities, not a running process. Defining an agent starts nothing and grants nothing.
 */
export interface AgentDefinition {
  schemaVersion: 1;
  id: Identifier;
  name: Line;
  status: "implemented" | "experimental" | "planned";
  purpose: Text;
  responsibilities: Notes;
  requiredContext: Notes1;
  /**
   * Capabilities the role is allowed to use. Anything absent is denied by default.
   *
   * @minItems 1
   * @maxItems 32
   */
  capabilities: [string, ...string[]];
  /**
   * Procedures this role follows. The role must hold every capability those procedures need.
   *
   * @minItems 1
   * @maxItems 32
   */
  skills: [Identifier, ...Identifier[]];
  forbidden: Notes2;
  inputs: Notes3;
  outputs: Notes3;
  escalation: Notes4;
}
