/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Identifier = string;
export type Text = string;
export type Line = string;
/**
 * @minItems 1
 * @maxItems 32
 */
export type Notes = [Note, ...Note[]];
export type Note = string;
/**
 * Roles this part stands for. Each must be a registered agent.
 *
 * @minItems 1
 * @maxItems 32
 */
export type Identifiers = [Identifier, ...Identifier[]];
/**
 * Procedures used here. Each must be a registered skill.
 *
 * @minItems 1
 * @maxItems 32
 */
export type Identifiers1 = [Identifier, ...Identifier[]];

/**
 * AX Harness v1 architecture map. Declares the parts of the harness and how a request flows between them. Nodes reference the real roles, procedures and capabilities they stand for, so the map cannot describe something the harness does not define.
 */
export interface ArchitectureDefinition {
  schemaVersion: 1;
  id: Identifier;
  description: Text;
  /**
   * @minItems 2
   * @maxItems 64
   */
  nodes: [Node, Node, ...Node[]];
  /**
   * @minItems 1
   * @maxItems 128
   */
  edges: [Edge, ...Edge[]];
}
export interface Node {
  id: Identifier;
  title: Line;
  /**
   * Drives presentation only. It grants nothing and implies no capability.
   */
  kind: "actor" | "artifact" | "core" | "agent" | "tools" | "quality" | "review";
  /**
   * Layer from the top of the map.
   */
  row: number;
  /**
   * Position within the layer. A renderer centres each row.
   */
  column: number;
  /**
   * What this part is.
   */
  summary: string;
  /**
   * Why it exists, rather than what it contains.
   */
  why: string;
  responsibilities: Notes;
  inputs: Notes;
  outputs: Notes;
  agents?: Identifiers;
  skills?: Identifiers1;
  /**
   * Capabilities involved. Each must exist in the policy vocabulary.
   *
   * @minItems 1
   * @maxItems 32
   */
  capabilities?: [string, ...string[]];
  /**
   * A definition whose real source a reader can inspect for this node.
   */
  reference?: {
    kind: "profile" | "agent" | "skill" | "adapter" | "policy" | "pipeline" | "workflow" | "eval" | "run";
    id: Identifier;
  };
}
export interface Edge {
  from: Identifier;
  to: Identifier;
  /**
   * flow is the forward path, failure returns for rework, feedback improves the harness itself.
   */
  kind: "flow" | "failure" | "feedback";
  label?: Line;
}
