/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Identifier = string;
export type Text = string;
export type Note = string;
/**
 * Work actually finished, as distinct from work attempted.
 *
 * @minItems 0
 * @maxItems 64
 */
export type List = Note[];
/**
 * @minItems 0
 * @maxItems 64
 */
export type List1 = Note[];
/**
 * Empty means there are none, not that the question was skipped.
 *
 * @minItems 0
 * @maxItems 64
 */
export type List2 = Note[];
/**
 * Recorded so the next session does not repeat them.
 *
 * @minItems 0
 * @maxItems 64
 */
export type List3 = Note[];
/**
 * What was verified, and what was explicitly not verified.
 *
 * @minItems 0
 * @maxItems 64
 */
export type List4 = Note[];

/**
 * AX Harness v1 handoff. Enough state for another session to continue without rebuilding context. Blockers and failed attempts are required keys so that omitting them is impossible: an empty list is an explicit claim that there were none.
 */
export interface HandoffRecord {
  schemaVersion: 1;
  id: Identifier;
  goal: Text;
  status: "complete" | "partial" | "blocked" | "abandoned";
  completed: List;
  changedFiles: List1;
  decisions: List1;
  blockers: List2;
  failedAttempts: List3;
  nextSteps: List1;
  validation: List4;
}
