/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Identifier = string;
export type Text = string;
export type Line = string;

/**
 * AX Harness v1 quality pipeline. Declares the ordered stages and which project quality flag and command each stage reads. Planning a pipeline never runs a stage.
 */
export interface PipelineDefinition {
  schemaVersion: 1;
  id: Identifier;
  description: Text;
  /**
   * Ordered. A later stage is only meaningful once earlier ones have passed.
   *
   * @minItems 1
   * @maxItems 32
   */
  stages: [Stage, ...Stage[]];
}
export interface Stage {
  id: Identifier;
  title: Line;
  /**
   * executable runs a declared command; eval assesses agent behavior; human requires a person.
   */
  kind: "executable" | "eval" | "human";
  /**
   * Project quality flag that decides whether this stage applies.
   */
  quality:
    "build" | "lint" | "typecheck" | "tests" | "integration_tests" | "security" | "review" | "eval" | "human_approval";
  /**
   * Resolved command slot. Required for executable stages and forbidden otherwise.
   */
  command?: "build" | "lint" | "typecheck" | "test" | "integration_test" | "security";
  description: Text;
}
