/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Identifier = string;
export type Text = string;
export type Line = string;

/**
 * AX Harness v1 capability vocabulary. A policy states which capabilities exist, which tool each needs, which require human approval, and which are denied to every agent. It is a declaration; no runtime enforces it.
 */
export interface PolicyDefinition {
  schemaVersion: 1;
  id: Identifier;
  description: Text;
  /**
   * @minItems 1
   * @maxItems 64
   */
  capabilities: [Capability, ...Capability[]];
}
export interface Capability {
  id: string;
  title: Line;
  description: Text;
  /**
   * Project tool switch this capability depends on, matching .ax/project.yaml tools.
   */
  tool: "codebase" | "docs" | "github" | "database" | "none";
  risk: "low" | "medium" | "high";
  /**
   * High-impact action that requires explicit human approval before use.
   */
  humanApproval: boolean;
  /**
   * No agent definition may claim this capability.
   */
  deniedToAllAgents: boolean;
}
