/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Single path segment. Directory separators and traversal are forbidden.
 */
export type FileName = string;
/**
 * @minItems 1
 * @maxItems 16
 */
export type Arguments =
  | [Argument]
  | [Argument, Argument]
  | [Argument, Argument, Argument]
  | [Argument, Argument, Argument, Argument]
  | [Argument, Argument, Argument, Argument, Argument]
  | [Argument, Argument, Argument, Argument, Argument, Argument]
  | [Argument, Argument, Argument, Argument, Argument, Argument, Argument]
  | [Argument, Argument, Argument, Argument, Argument, Argument, Argument, Argument]
  | [Argument, Argument, Argument, Argument, Argument, Argument, Argument, Argument, Argument]
  | [Argument, Argument, Argument, Argument, Argument, Argument, Argument, Argument, Argument, Argument]
  | [Argument, Argument, Argument, Argument, Argument, Argument, Argument, Argument, Argument, Argument, Argument]
  | [
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument
    ]
  | [
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument
    ]
  | [
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument
    ]
  | [
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument
    ]
  | [
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument,
      Argument
    ];
/**
 * Whitespace-free token, so that joining arguments is unambiguous without quoting.
 */
export type Argument = string;
export type Note = string;

/**
 * AX Harness v1 stack profile. A profile supplies command defaults and documented assumptions. It never grants capabilities, relaxes permissions, enables quality gates, or proves that a toolchain is installed.
 */
export interface ProfileDefinition {
  schemaVersion: 1;
  /**
   * Must equal the built-in registry key that exposes this definition.
   */
  id: string;
  status: "implemented" | "experimental" | "planned";
  description: string;
  /**
   * Supported build systems. Manifest presence is evidence of layout only.
   */
  buildSystems: {
    maven?: BuildSystem;
    gradle?: BuildSystem;
    node?: BuildSystem;
  };
  /**
   * Assumptions a reviewer should preserve. Assumptions are not verified facts about any project.
   *
   * @minItems 1
   * @maxItems 32
   */
  architecture: [Note, ...Note[]];
  /**
   * Explicit statements of what this profile does not establish or supply.
   *
   * @minItems 1
   * @maxItems 32
   */
  limitations: [Note, ...Note[]];
}
export interface BuildSystem {
  /**
   * Filenames looked up directly in the selected build root. Detection never recurses.
   *
   * @minItems 1
   * @maxItems 8
   */
  manifests:
    | [FileName]
    | [FileName, FileName]
    | [FileName, FileName, FileName]
    | [FileName, FileName, FileName, FileName]
    | [FileName, FileName, FileName, FileName, FileName]
    | [FileName, FileName, FileName, FileName, FileName, FileName]
    | [FileName, FileName, FileName, FileName, FileName, FileName, FileName]
    | [FileName, FileName, FileName, FileName, FileName, FileName, FileName, FileName];
  runner: {
    wrapper?: {
      posix: RunnerForm;
      windows: RunnerForm;
    };
    /**
     * Used when no wrapper is present. Its availability on PATH is never verified.
     */
    fallback: string;
  };
  /**
   * Gate command defaults. Omit a gate the profile cannot honestly supply.
   */
  commands: {
    build?: Arguments;
    lint?: Arguments;
    typecheck?: Arguments;
    test?: Arguments;
    integration_test?: Arguments;
    security?: Arguments;
  };
}
export interface RunnerForm {
  /**
   * Single path segment. Directory separators and traversal are forbidden.
   */
  file: string;
  /**
   * Platform invocation form for that wrapper.
   */
  command: string;
}
