/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Relative Markdown path, using forward slashes. Parent traversal and absolute paths are forbidden. File containment is verified separately.
 */
export type ContextPath = string;
/**
 * Opaque single-line command declaration; never evaluated by the validator.
 */
export type Command = string;

/**
 * AX Harness v1 project declaration. Validation never executes commands or grants capabilities.
 */
export interface ProjectConfig {
  schemaVersion: 1;
  project: {
    name: string;
    /**
     * Multi-repository execution is planned, not implemented.
     */
    mode: "single-repo";
    /**
     * Identifier only in Phase 2; profile existence and resolution are not yet checked.
     */
    profile: string;
  };
  context: {
    architecture?: ContextPath;
    domain?: ContextPath;
    database?: ContextPath;
  };
  commands: {
    build?: Command;
    lint?: Command;
    typecheck?: Command;
    test?: Command;
    integration_test?: Command;
    security?: Command;
  };
  tools: {
    codebase: Tool;
    docs: Tool;
    github: Tool;
    database: {
      enabled: boolean;
      mode: "metadata-only";
    };
  };
  permissions: {
    direct_main_push: false;
    force_push: false;
    production_deploy: false;
    database_write: false;
    secrets_access: false;
  };
  quality: {
    build: boolean;
    lint: boolean;
    typecheck: boolean;
    tests: boolean;
    integration_tests: boolean;
    security: boolean;
    review: true;
    eval: boolean;
    human_approval: true;
  };
  limits: {
    max_retries: number;
    max_duration_seconds: number;
  };
}
export interface Tool {
  enabled: boolean;
}
