/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * AX Harness v1 run record. Recorded runs require local-executor provenance and execution evidence; examples are illustrative and cannot claim that provenance.
 */
export type RunRecord = {
  [k: string]: unknown;
} & {
  schemaVersion: 1;
  id: Identifier;
  /**
   * example is illustrative. recorded requires evidence produced by the controlled local executor.
   */
  kind: "example" | "recorded";
  source?: "local-executor";
  project?: Identifier;
  startedAt?: Timestamp;
  finishedAt?: Timestamp;
  durationMs?: number;
  finalStatus?: "pass" | "fail" | "incomplete";
  task: Text;
  /**
   * Role that owned the task.
   */
  agent?: string;
  profile: Identifier;
  status?: "completed" | "failed" | "blocked" | "abandoned";
  /**
   * Omit when the duration was not measured.
   */
  durationSeconds?: number;
  retries: number;
  /**
   * @minItems 0
   * @maxItems 16
   */
  tools:
    | []
    | ["codebase" | "docs" | "github" | "database"]
    | ["codebase" | "docs" | "github" | "database", "codebase" | "docs" | "github" | "database"]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ];
  filesRead: Paths;
  filesChanged: Paths;
  /**
   * @minItems 0
   * @maxItems 32
   */
  gates: {
    stage: Identifier;
    /**
     * unavailable and unrun are distinct from passed and must never be reported as a pass.
     */
    outcome: "passed" | "failed" | "timed-out" | "execution-error" | "unavailable" | "unrun";
    title?: Line;
    command?: string | null;
    reason?: string | null;
    execution?: Execution;
  }[];
  eval?: {
    id: Identifier;
    percent: number;
    passed: boolean;
  };
  /**
   * Omit any field that was not measured. An absent field means unmeasured, not zero.
   */
  measurements?: {
    inputTokens?: number;
    outputTokens?: number;
    costUsd?: number;
  };
  notes: Notes;
};
export type Identifier = string;
export type Timestamp = string;
export type Text = string;
export type Path = string;
/**
 * @minItems 0
 * @maxItems 64
 */
export type Paths = Path[];
export type Line = string;
/**
 * @minItems 1
 * @maxItems 32
 */
export type Notes = [Note, ...Note[]];
export type Note = string;

export interface Execution {
  program: string | null;
  /**
   * @maxItems 128
   */
  args: string[];
  startedAt: Timestamp;
  finishedAt: Timestamp;
  durationMs: number;
  exitCode: number | null;
  status: "passed" | "failed" | "timed-out" | "unsupported" | "execution-error";
  timedOut: boolean;
  outputTruncated: boolean;
  unsupportedReason?: "empty" | "shell-syntax";
  errorCode?: string;
}
