/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Identifier = string;
export type Text = string;
export type Path = string;
/**
 * @minItems 0
 * @maxItems 64
 */
export type Paths = Path[];
/**
 * @minItems 1
 * @maxItems 32
 */
export type Notes = [Note, ...Note[]];
export type Note = string;

/**
 * AX Harness v1 run record. Describes one task execution. The kind field is required so an illustrative record can never be mistaken for a real one, and measurements are optional because an absent measurement means unmeasured, never zero.
 */
export interface RunRecord {
  schemaVersion: 1;
  id: Identifier;
  /**
   * example is illustrative and was never executed. recorded requires a real execution, which no current component can produce.
   */
  kind: "example" | "recorded";
  task: Text;
  /**
   * Role that owned the task.
   */
  agent: string;
  profile: Identifier;
  status: "completed" | "failed" | "blocked" | "abandoned";
  /**
   * Omit when the duration was not measured.
   */
  durationSeconds?: number;
  retries: number;
  /**
   * @minItems 0
   * @maxItems 16
   */
  tools:
    | []
    | ["codebase" | "docs" | "github" | "database"]
    | ["codebase" | "docs" | "github" | "database", "codebase" | "docs" | "github" | "database"]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ]
    | [
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database",
        "codebase" | "docs" | "github" | "database"
      ];
  filesRead: Paths;
  filesChanged: Paths;
  /**
   * @minItems 0
   * @maxItems 32
   */
  gates: {
    stage: Identifier;
    /**
     * unavailable and unrun are distinct from passed and must never be reported as a pass.
     */
    outcome: "passed" | "failed" | "unavailable" | "unrun";
  }[];
  eval?: {
    id: Identifier;
    percent: number;
    passed: boolean;
  };
  /**
   * Omit any field that was not measured. An absent field means unmeasured, not zero.
   */
  measurements?: {
    inputTokens?: number;
    outputTokens?: number;
    costUsd?: number;
  };
  notes: Notes;
}
