/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Identifier = string;
export type Line = string;
export type Text = string;
/**
 * @minItems 1
 * @maxItems 32
 */
export type Notes = [Note, ...Note[]];
export type Note = string;
/**
 * Ordered procedure. Order is meaningful.
 *
 * @minItems 1
 * @maxItems 32
 */
export type Notes1 = [Note, ...Note[]];
/**
 * How to tell the procedure was actually followed.
 *
 * @minItems 1
 * @maxItems 32
 */
export type Notes2 = [Note, ...Note[]];
/**
 * When to stop and hand back to a human.
 *
 * @minItems 1
 * @maxItems 32
 */
export type Notes3 = [Note, ...Note[]];

/**
 * AX Harness v1 skill. A skill is a reusable procedure, not a worker. Defining a skill does not execute it and does not grant the capabilities it lists.
 */
export interface SkillDefinition {
  schemaVersion: 1;
  id: Identifier;
  name: Line;
  status: "implemented" | "experimental" | "planned";
  purpose: Text;
  prerequisites: Notes;
  steps: Notes1;
  /**
   * Capabilities this procedure needs. Every agent listing this skill must hold all of them.
   *
   * @minItems 1
   * @maxItems 32
   */
  capabilities: [string, ...string[]];
  outputs: Notes;
  verification: Notes2;
  escalation: Notes3;
}
