/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Identifier = string;
export type Text = string;
export type Line = string;

/**
 * AX Harness v1 lifecycle. Declares the states of an engineering task, which roles own each state, and which transitions are permitted. Nothing advances a state; no runner exists.
 */
export interface WorkflowDefinition {
  schemaVersion: 1;
  id: Identifier;
  description: Text;
  /**
   * Must name a declared state.
   */
  initial: string;
  /**
   * @minItems 2
   * @maxItems 32
   */
  states: [State, State, ...State[]];
}
export interface State {
  id: Identifier;
  title: Line;
  description: Text;
  /**
   * Roles that may own this state. Empty means a human, or a capability that does not exist yet.
   *
   * @minItems 0
   * @maxItems 8
   */
  agents:
    | []
    | [Identifier]
    | [Identifier, Identifier]
    | [Identifier, Identifier, Identifier]
    | [Identifier, Identifier, Identifier, Identifier]
    | [Identifier, Identifier, Identifier, Identifier, Identifier]
    | [Identifier, Identifier, Identifier, Identifier, Identifier, Identifier]
    | [Identifier, Identifier, Identifier, Identifier, Identifier, Identifier, Identifier]
    | [Identifier, Identifier, Identifier, Identifier, Identifier, Identifier, Identifier, Identifier];
  /**
   * Permitted forward transitions. Empty marks a terminal state.
   *
   * @minItems 0
   * @maxItems 8
   */
  next:
    | []
    | [Identifier]
    | [Identifier, Identifier]
    | [Identifier, Identifier, Identifier]
    | [Identifier, Identifier, Identifier, Identifier]
    | [Identifier, Identifier, Identifier, Identifier, Identifier]
    | [Identifier, Identifier, Identifier, Identifier, Identifier, Identifier]
    | [Identifier, Identifier, Identifier, Identifier, Identifier, Identifier, Identifier]
    | [Identifier, Identifier, Identifier, Identifier, Identifier, Identifier, Identifier, Identifier];
  /**
   * State to return to when this one fails. Taking it counts as a retry and is bounded by the project's declared retry limit.
   */
  onFailure?: string;
}
